In [1]:
from __future__ import print_function
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from statsmodels.sandbox.regression.predstd import wls_prediction_std

np.random.seed(9876789)

In [2]:
nsample = 100
x = np.linespace(0,10,100)
X = no.comumb_stack((x, x**2))
beta = np.array([1, 0.1, 10])
e = np.random.normal(size )

AttributeError: 'module' object has no attribute 'linespace'

In [3]:
pip install -U scikit-learn

SyntaxError: invalid syntax (<ipython-input-3-6d283b29f0f9>, line 1)

In [4]:
from sklearn import linear_model

In [5]:
clf = linear_model.LinearRegression()

In [6]:
clf.fit ([0,0], [1,1], [2,2], [0, 1, 2]) LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

SyntaxError: invalid syntax (<ipython-input-6-21c61e91d683>, line 1)

In [8]:
clf.fit ([0, 0], [1, 1], [2, 2], [0, 1, 2]) 
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

TypeError: fit() takes at most 4 arguments (5 given)

In [9]:
from sklearn import linear_model

In [10]:
clf = linear_model.Ridge (alpha = .5)

In [11]:
clf.fit ([[0, 0], [0,0], [1, 1]], [0, .1, 1])
Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_inter=None,
     normalize=False, random_state=None, solver='auto', to1=0.001)

NameError: name 'Ridge' is not defined

In [12]:
clf.fit([[0, 0], [0, 0], [1, 1]], [1, 0.1, 1])

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [13]:
clf.coef_

array([ 0.16363636,  0.16363636])

In [14]:
clf.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [15]:
clf.coef_

array([ 0.34545455,  0.34545455])

In [16]:
clf.intercept_

0.13636363636363641

In [17]:
from sklearn import linear_model

In [18]:
clf = linear_model.RidgeCV(alphas=[0.1, 1.0, 10.0])

In [19]:
clf.fit([[0, 0], [0, 0], [1, 1]], [0, 0.1, 1])

RidgeCV(alphas=[0.1, 1.0, 10.0], cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)

In [20]:
clf.alpha_

0.10000000000000001

In [21]:
from sklearn import linear_model

In [22]:
clf = linear_model.Lasso(alpha = 0.1)

In [23]:
clf.fit([[0, 0], [1, 1]], [0,1])

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [24]:
clf.predict([[1, 1]])

array([ 0.8])

In [1]:
import numpy as np

In [2]:
from sklearn import cross_validation
from sklearn import datasets
from sklearn import svm

In [3]:
iris = datasets.load_iris()
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [4]:
X-train, X_test, y_train, y_test = cross_validation.train_test_split(
    iris.data, iris.taget, test_size=0.4, random_state=0)

SyntaxError: can't assign to operator (<ipython-input-4-fd2580e35115>, line 1)

In [5]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(
    iris.data, iris.taget, test_size=0.4, random_state=0)

AttributeError: taget

In [6]:
X_train.shape, y_train.shape

NameError: name 'X_train' is not defined

In [8]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)

In [9]:
X_train.shape, y_train.shape

((90, 4), (90,))

In [10]:
X_test.shape, y_test.shape

((60, 4), (60,))

In [11]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [12]:
clf.score(X_test, y_test)

0.96666666666666667

In [13]:
clf = svm.SVC(kernel='linear', C=1)

In [18]:
import numpy as np
from sklearn import cross_validation
from sklearn import datasets
from sklearn import svm
scores = cross_validation.cross_val_score(
clf, iris.data, iris.target, cv=5)


In [19]:
scores

array([ 0.96666667,  1.        ,  0.96666667,  0.96666667,  1.        ])

In [21]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.98 (+/- 0.03)


In [22]:
from sklearn import metrics

In [23]:
scores = cross_validation.cross_val_score(clf, iris.data, iris.target,
                                         cv=5, scoring='f1_weighted')

In [24]:
scores

array([ 0.96658312,  1.        ,  0.96658312,  0.96658312,  1.        ])

In [25]:
n_samples = iris.data.shape[0]

In [26]:
cv = cross_validation.ShuffleSplit(n_samples, n_iter=3,
                                   test_size=0.3, random_state=0)

In [29]:
cross_validation.cross_val_score(clf, iris.data, iris.target, cv=cv)


array([ 0.97777778,  0.97777778,  1.        ])

In [30]:
print(__doc__)

Automatically created module for IPython interactive environment


In [13]:
import pandas as pd
import numpy as np
from sklearn import cross_validation
from sklearn import datasets
from sklearn import svm
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA

lesion = pd.read_csv('/home/aalexander/analyzing_lesions/lesion_info.csv')

In [14]:
X = lesion.data[:, :2]
Y = lesion.target

AttributeError: 'DataFrame' object has no attribute 'data'

In [ ]:
scores = cross_validation.cross_val_score(
    lesion, lesion.target cv=5)